version: '3.4'

services:
  db:
    container_name: "db"
    image: microsoft/mssql-server-windows-express
    environment:
      - SA_PASSWORD=Pass@word1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  saascommerce:
    container_name: "SaaSCommerce"
    depends_on: 
      - "db"
    ports:
      - "8080:80"
    environment:    
      - "Data:DefaultConnection:ConnectionString=Server=db,1433;Database=SaaSCommerce;User Id=sa;Password=Pass@word1;MultipleActiveResultSets=True"
    build:
      context: ./SaaSCommerce
      dockerfile: Dockerfile

