version: '3.4'

services:
  db:
    container_name: "db"
    image: microsoft/mssql-server-windows-express
    environment:
      sa_password: Pass@word1
      accept_eula: Y
      attach_dbs: '[{"dbName":"saascommerce","dbFiles":["C:\\data\\saascommerce.mdf","C:\\data\\saascommerce.ldf"]}]'
    ports:
      - "1433:1433"
    volumes:
      - "c:\\src\\data:c:\\data"
  saascommerce:
    container_name: "SaaSCommerce"
    depends_on: 
      - "db"
    ports:
      - "8080:80"
    environment:    
      - "Data:DefaultConnection:ConnectionString=Server=db,1433;Database=SaaSCommerce;User Id=sa;Password=Pass@word1;MultipleActiveResultSets=True"
    build:
      context: ./SaaSCommerce
      dockerfile: Dockerfile


